[tool.poetry]
name = "azcam-lbtguiders"
version = "22.3"
description = "Azcam extension for LBTO lbtguiders cameras"
authors = ["Michael Lesser <mlesser@arizona.edu>"]
license = "LICENSE"
readme = "README.md"
keywords=["ccd", "imaging", "astronomy", "sensors"]
repository = "https://github.com/mplesser/azcam-lbtguiders/"
documentation = "https://mplesser.github.io/azcam/"

[tool.poetry.dependencies]
python = "^3.9,<3.11"
ipython = "*"
PySide2 = "*"
rich = "*"

azcam = { git = "https://github.com/mplesser/azcam.git"}
azcam-monitor = { git = "https://github.com/mplesser/azcam-monitor.git"}
azcam-fastapi = { git = "https://github.com/mplesser/azcam-fastapi.git"}
azcam-arc = { git = "https://github.com/mplesser/azcam-arc.git"}
azcam-ds9 = { git = "https://github.com/mplesser/azcam-ds9.git"}
azcam-imageserver = { git = "https://github.com/mplesser/azcam-imageserver.git"}
azcam-mag = { git = "https://github.com/mplesser/azcam-mag.git"}
azcam-webtools = { git = "https://github.com/mplesser/azcam-webtools.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
